name: PyInstaller Build macOS

on:
  push:
    tags: ['v*']
  pull_request:
    tags: ['v*']

jobs:
  build:
    name: Build Release
    runs-on: macos-latest
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2

    - name: Set Up Python Environment
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip wheel setuptools pyinstaller
        (test -f requirements.txt && pip install -r requirements.txt) || echo "'requirements.txt' does not exist, skipping dependency installation"
    - name: Build macOS Executable
      run: |
        pyinstaller --clean --noconsole --windowed --onefile -y --dist ./dist/macos build.spec main.py
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        files: ./dist/macos/*
